name: dart_vercel
description: An Vercel Edge function written in Dart.
version: 1.0.0
publish_to: none

environment:
  sdk: ">=2.18.5 <3.0.0"

dependencies:
  cloudflare_workers: ^0.0.3+2
  edge: ^0.0.5
  vercel_edge: ^0.0.3+2
  shelf: ^1.4.0
  shelf_router: ^1.1.3
  js: ^0.6.7
  edge_runtime: 
  

dev_dependencies:
  lints: ^2.0.1 